# Generated by Django 2.1.3 on 2019-05-09 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_exchange_organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domainorganization',
            options={},
        ),
    ]
